### PR TITLE
New serial protocol with headers

### PR DESCRIPTION
**Pull request by jast1982**
Implemented new serial protocol V3.5 with headers and no timing
constraints
Now running baudrate of 125000 baud (-> no fractional BR divider at
16Mhz in Atmel, therefore non-standard for best performance)
Baudrate tested up to 500.000baud without errors
Intensive statistics for link
Read to add debugging
Initial testing and stress testing completed

### CODE REVIEW

**Comment by jast1982** [comment]
Please test and review. I didn't look into the packet contents. The only changes I did were removing CRC, protocolVersion and sequence number since they are now part of the outer package definition

**Comment by jast1982** [comment]
Currently the serial statistics is logged as warning and also shown on the console. Once everything is tested we should change it to debug

**Review by BrianWoodruff — APPROVED** [review]
This all looks good to me.  It'd be nice to have some comments in the state machine as I had to go back to the doc to understand the flow.

**Comment by noelpaz** [comment]
The in_packet.py and params.py are not properly updated. The limit fields are not added .  I recommend to fix those first and do more testing.

**Review by noelpaz — CHANGES_REQUESTED** [review]
Based on the .35 protocol  doc, some fields need to be added to in_packet.py, out_packet.py and in params.py.  The limit fields come to mind and there could be others missed. We also need to test with static values from lik.cpp or if an end to end system is available - use that also

**Comment by BrianWoodruff** [comment]
The content of this PR was incorporated into PR 101.

**Pull request closed without merging**
