### PR TITLE
Converted project into a proper python3 package.

### PR DESCRIPTION
**Pull request by zmk5**
This should make it easier for us when we want to mass deploy this onto a thousand ventilators.

### CODE REVIEW

**Review by avigupta33 — COMMENTED** [review]
Instead of a dictionary, would it make more sense for the numerical attributes to be a list?

**Comment by zmk5** [comment]
That is an interesting point :-) In Python, string dictionary key lookups are faster than integer dictionary key lookups or lists.

[This](https://stackoverflow.com/a/513906) guy gives a good explanation.

**Comment by avigupta33** [comment]
Interesting! Good to know :)

**Comment by BrianWoodruff** [comment]
Looks good, thank you.

**Pull request merged**
